// Auto-generated by OpenLane
module lowpass(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input[3:0] tap,
  input[239:0] input_data,
  output[15:0] output_low
);
endmodule
