// Auto-generated by OpenLane
module top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[15:0] input_signal,
  input[3:0] tap,
  input clk,
  input rst,
  output[15:0] filtered_signal
);
endmodule
